version: '3'
services:
  games_server:
    build:
      context: server/.
    volumes:
      - ./:/src
      - /src/frontend
    ports:
      - 4000:4000
    working_dir: /src/server
    command: npm run install-and-start

  games_frontend:
    build:
      context: frontend/.
    volumes:
      - ./:/src
      - /src/server
    ports:
      - 3000:3000
    working_dir: /src/frontend
    command: npm run install-and-start