version: '3'
services:
  games_server:
    build:
      context: server/.
    volumes:
      - ./server:/src
      - /src/node_modules
    ports:
      - 4000:4000
    working_dir: /src
    command: npm start

  games_frontend:
    build:
      context: frontend/.
    volumes:
      - ./frontend:/src
      - /src/node_modules
    ports:
      - 3000:3000
    working_dir: /src