version: '3'
services:
  games:
    build:
      context: server/.
    volumes:
      - ./server:/src
      - /src/node_modules
    ports:
      - 4000:4000
    working_dir: /src
    command: ./scripts/init.sh
