version: '3'
services:
  games_server:
    build:
      context: server/.
    volumes:
      - ./server:/src
    ports:
      - 4000:4000
    working_dir: /src
    command: npm run install-and-start

  games_frontend:
    build:
      context: frontend/.
    volumes:
      - ./frontend:/src
    ports:
      - 3000:3000
    working_dir: /src
    command: npm run install-and-start